
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { ProjectFile } from '../types';

export const projectFiles: ProjectFile = {
    name: 'flash-ui-app',
    children: [
        {
            name: 'src',
            children: [
                {
                    name: 'components',
                    children: [
                        { name: 'Header.tsx', content: `
import React from 'react';

export default function Header() {
  return (
    <header className="app-header">
      <h1>Flash UI</h1>
      <nav>
        <a href="#home">Home</a>
        <a href="#about">About</a>
      </nav>
    </header>
  );
}
` },
                        { name: 'Button.tsx', content: `
import React from 'react';

interface ButtonProps {
  onClick: () => void;
  children: React.ReactNode;
  variant?: 'primary' | 'secondary';
}

export const Button = ({ onClick, children, variant = 'primary' }: ButtonProps) => {
  return (
    <button 
      onClick={onClick}
      className={\`btn btn-\${variant}\`}
    >
      {children}
    </button>
  );
};
` },
                        { name: 'Card.tsx', content: `import React from 'react';

export const Card = ({ title, children }: any) => (
  <div className="card">
    <h3>{title}</h3>
    <div className="card-body">{children}</div>
  </div>
);` }
                    ]
                },
                {
                    name: 'utils',
                    children: [
                        { name: 'helpers.ts', content: `
export const formatDate = (date: Date) => {
  return new Intl.DateTimeFormat('en-US').format(date);
};

export const capitalize = (str: string) => {
  return str.charAt(0).toUpperCase() + str.slice(1);
};
` },
                        { name: 'api.ts', content: `
export const fetchData = async (endpoint: string) => {
  const response = await fetch(endpoint);
  return response.json();
};
` }
                    ]
                },
                { name: 'App.tsx', content: `
import React from 'react';
import Header from './components/Header';
import { Button } from './components/Button';

function App() {
  return (
    <div className="app">
      <Header />
      <main>
        <h2>Welcome to Flash UI</h2>
        <Button onClick={() => alert('Clicked!')}>Get Started</Button>
      </main>
    </div>
  );
}

export default App;
` },
                { name: 'main.tsx', content: `
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
` },
                { name: 'index.css', content: `
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  -webkit-font-smoothing: antialiased;
}

.app { text-align: center; }
.btn { padding: 8px 16px; border-radius: 4px; cursor: pointer; }
` }
            ]
        },
        {
            name: 'public',
            children: [
                { name: 'manifest.json', content: `{
  "name": "Flash UI App",
  "short_name": "FlashUI",
  "start_url": ".",
  "display": "standalone"
}` },
                { name: 'robots.txt', content: `User-agent: *\nAllow: /` }
            ]
        },
        { name: 'package.json', content: `
{
  "name": "flash-ui-app",
  "version": "1.0.0",
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}
` },
        { name: 'tsconfig.json', content: `
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "jsx": "react-jsx",
    "strict": true
  }
}
` },
        { name: 'README.md', content: `# Flash UI Project\n\nGenerated by AI.` }
    ]
};
